import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
const migration=await fs.readFile(new URL('../supabase/migrations/202610030001_household.sql',import.meta.url),'utf8');
const db=new PGlite();await db.exec('CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;');await db.exec(migration);await db.exec(await fs.readFile(new URL('../supabase/migrations/202610030002_daily_review.sql',import.meta.url),'utf8'));
const user='11111111-1111-4111-8111-111111111111',partner='22222222-2222-4222-8222-222222222222',stranger='33333333-3333-4333-8333-333333333333';
const settings={you:'Alex',partner:'Sam',defaultShare:50,budgets:{Groceries:60000}};
const hid=(await db.query('SELECT create_household($1,$2,$3) AS id',[user,settings,'invite-hash'])).rows[0].id;
const txn={id:'manual-test',date:'2025-01-01',merchant:'Test groceries',amount:12000,payer:'you',kind:'expense',category:'Groceries',share:50,note:'',reviewed:0};
test('Invite joins exactly two people and cannot be reused',async()=>{await db.query('SELECT join_household($1,$2)',[partner,'invite-hash']);await assert.rejects(db.query('SELECT join_household($1,$2)',[stranger,'invite-hash']));assert.equal((await db.query('SELECT count(*)::int AS n FROM members WHERE household_id=$1',[hid])).rows[0].n,2);});
test('Old backlog persists, a review saves, and stale edits are rejected',async()=>{await db.query('SELECT save_transaction($1,$2)',[hid,txn]);let row=(await db.query('SELECT * FROM transactions WHERE household_id=$1 AND id=$2',[hid,txn.id])).rows[0];assert.equal(row.reviewed,0);assert.equal(new Date(row.date).toISOString().slice(0,10),'2025-01-01');const update={...txn,reviewed:1,updated:row.updated};await db.query('SELECT save_transaction($1,$2)',[hid,update]);await assert.rejects(db.query('SELECT save_transaction($1,$2)',[hid,update]));row=(await db.query('SELECT * FROM transactions WHERE household_id=$1 AND id=$2',[hid,txn.id])).rows[0];assert.equal(row.reviewed,1);});
test('Anonymous and authenticated clients cannot directly read financial tables or invoke service RPCs',async()=>{for(const role of ['anon','authenticated']){await db.exec('SET ROLE '+role);await assert.rejects(db.query('SELECT * FROM transactions'));await assert.rejects(db.query('SELECT * FROM bank_items'));await assert.rejects(db.query('SELECT save_transaction($1,$2)',[hid,txn]));await db.exec('RESET ROLE');}});
test('Bank sync is idempotent, preserves reviews, and requeues corrected amounts',async()=>{await db.query('INSERT INTO bank_items(id,household_id,token,payer,institution) VALUES($1,$2,$3,$4,$5)',['item',hid,'encrypted-token','you','Test bank']);const row={...txn,id:'bank-1',pending:0,account:'Test bank'};await db.query('SELECT apply_bank_sync($1,$2,$3,$4,$5)',[hid,'item',[row],[],'cursor-1']);let saved=(await db.query('SELECT * FROM transactions WHERE id=$1',['bank-1'])).rows[0];await db.query('SELECT save_transaction($1,$2)',[hid,{...saved,reviewed:1}]);await db.query('SELECT apply_bank_sync($1,$2,$3,$4,$5)',[hid,'item',[row],[],'cursor-2']);saved=(await db.query('SELECT * FROM transactions WHERE id=$1',['bank-1'])).rows[0];assert.equal(saved.reviewed,1);await db.query('SELECT apply_bank_sync($1,$2,$3,$4,$5)',[hid,'item',[{...row,amount:13000}],[],'cursor-3']);saved=(await db.query('SELECT * FROM transactions WHERE id=$1',['bank-1'])).rows[0];assert.equal(saved.reviewed,0);assert.equal(saved.amount,13000);assert.equal((await db.query('SELECT count(*)::int AS n FROM transactions WHERE id=$1',['bank-1'])).rows[0].n,1);});
test('Failed sync rolls back transaction changes and the cursor together',async()=>{await assert.rejects(db.query('SELECT apply_bank_sync($1,$2,$3,$4,$5)',[hid,'item',[{...txn,id:'bad-import',amount:0,pending:0,account:'Test'}],[],'bad-cursor']));assert.equal((await db.query('SELECT cursor FROM bank_items WHERE id=$1',['item'])).rows[0].cursor,'cursor-3');});
test('Pending transactions cannot be approved',async()=>{await db.query('SELECT apply_bank_sync($1,$2,$3,$4,$5)',[hid,'item',[{...txn,id:'pending-test',pending:1,account:'Test'}],[],'cursor-4']);const row=(await db.query('SELECT * FROM transactions WHERE id=$1',['pending-test'])).rows[0];await assert.rejects(db.query('SELECT save_transaction($1,$2)',[hid,{...row,reviewed:1}]));});
test.after(async()=>await db.close());


