'use client';
import {useEffect,useState} from 'react';
import {native} from './bridge';
import {Check,Inbox,ChartNoAxesCombined,Wallet,Landmark,Plus,RotateCw,ArrowDownLeft,X,CheckCheck,Clock3,Undo2,ChevronRight,Users} from 'lucide-react';
import {categories,defaults,dollars,localDay,samples,shares,summarize,type Transaction,type Settings} from './money';
type State={transactions:Transaction[];settings:Settings;items:any[];checkins:{day:string;at:string}[];bankReady:boolean;bankEnvironment:string;memberRole?:string;memberCount?:number};
const empty:State={transactions:[],settings:defaults,items:[],checkins:[],bankReady:false,bankEnvironment:'sandbox'};
async function api(path:string,body?:any){if(path==="bank")return native("bank/"+body.action,body);return native(path,body);}
const kindNames={expense:'Purchase',refund:'Refund',income:'Income / deposit',transfer:'Transfer / card payment',settlement:'Repayment between us'};
export default function Together({initialDemo=false,onExitDemo}:{initialDemo?:boolean;onExitDemo?:()=>void}){
 const [state,setState]=useState<State>(initialDemo?{...empty,transactions:samples(),settings:structuredClone(defaults)}:empty),[demo,setDemo]=useState(initialDemo),[view,setView]=useState('inbox'),[filter,setFilter]=useState('unreviewed'),[selected,setSelected]=useState<string|null>(null),[loading,setLoading]=useState(!initialDemo),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[signedOut,setSignedOut]=useState(false),[adding,setAdding]=useState(false),[month,setMonth]=useState(localDay().slice(0,7)),[sessionCount,setSessionCount]=useState(0);
 const refresh=async()=>{const data=await api('state');setState(data);setSignedOut(false);return data as State;};
 useEffect(()=>{if(initialDemo)return;refresh().then(async s=>{if(s.bankReady&&s.items.length){try{const r=await api('bank',{action:'sync'});if(r.errors?.length)setError(r.errors.join(' '));await refresh();}catch(e:any){setError(e.message);}}}).catch(e=>{setSignedOut(e.status===401);if(e.status!==401)setError(e.message);}).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(demo||signedOut)return;const focus=()=>{if(!busy)void refresh().catch(()=>{});};window.addEventListener('focus',focus);const timer=setInterval(()=>{if(document.visibilityState==='visible')focus();},30000);return()=>{window.removeEventListener('focus',focus);clearInterval(timer);};},[demo,signedOut,busy]);
 const transactions=state.transactions.filter(t=>!t.removed);
 const queue=transactions.filter(t=>!t.reviewed&&!t.pending).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));
 const pending=transactions.filter(t=>t.pending);
 const reviewed=transactions.filter(t=>t.reviewed&&!t.pending).sort((a,b)=>b.date.localeCompare(a.date));
 const list=filter==='reviewed'?reviewed:filter==='pending'?pending:queue;
 const current=list.find(t=>t.id===selected)||list[0];
 const totals=summarize(transactions,month),all=summarize(transactions);
 const s=state.settings;
 const checkedToday=state.checkins.some(c=>c.day===localDay());
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await action();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const saveTransaction=async(t:Transaction)=>{await run(async()=>{if(demo){setState(prev=>({...prev,transactions:prev.transactions.some(x=>x.id===t.id)?prev.transactions.map(x=>x.id===t.id?t:x):[...prev.transactions,{...t,reviewed:0}]}));}else{await api('transactions',t);await refresh();}if(t.reviewed)setSessionCount(n=>n+1);setSelected(null);setAdding(false);setNotice(t.reviewed?'Reviewed and saved.': 'Saved to your review inbox.');});};
 const saveSettings=async(settings:Settings)=>{await run(async()=>{if(demo)setState(p=>({...p,settings}));else{await api('settings',settings);await refresh();}setNotice('Changes saved.');});};
 const finish=()=>run(async()=>{if(demo)setState(p=>({...p,checkins:[...p.checkins,{day:localDay(),at:new Date().toISOString()}]}));else{await api('checkin',{day:localDay()});await refresh();}setNotice(queue.length?'Check-in saved. Your remaining transactions will be here next time.':'Check-in complete. You’re all caught up.');});
 const startDemo=()=>{setDemo(true);setState({...empty,transactions:samples(),settings:structuredClone(defaults)});setError('');setNotice('Sample mode. Changes here are for practice and are not saved.');setSignedOut(false);setLoading(false);setSelected(null);};
 const exitDemo=()=>run(async()=>{if(onExitDemo){onExitDemo();return;}setDemo(false);setState(empty);setSelected(null);try{await refresh();}catch(e:any){if(e.status===401)setSignedOut(true);else throw e;}});
 const sync=()=>run(async()=>{const result=await api('bank',{action:'sync'});await refresh();if(result.errors?.length)throw new Error(result.errors.join(' '));setNotice('Bank sync complete. New transactions are in your inbox.');});

 async function openLink(payer:string,itemId?:string){await run(async()=>{const data=await native('bank/open',{payer,itemId});setNotice('Your browser opened a secure Plaid connection. Finish there, then return here.');const deadline=Date.now()+10*60*1000;while(Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,4000));const result=await native('bank/poll',{sessionId:data.sessionId});if(result.complete){await refresh();if(result.errors?.length)throw new Error(result.errors.join(' '));setNotice('Bank connected. Your transactions are ready to review.');return;}}setNotice('Connection is taking longer than expected. Return to Accounts and try connecting again.');});}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'read_review_inbox',description:'Read all unreviewed transactions in the visible household, including older backlog. Does not approve or change transactions.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('No arguments are accepted.');return {sampleMode:demo,count:queue.length,transactions:queue.map(t=>({id:t.id,date:t.date,merchant:t.merchant,amountCents:t.amount,payer:t.payer,category:t.category}))};}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[state,demo]);
 const tabs=[['inbox','Review inbox',Inbox],['picture','Our picture',ChartNoAxesCombined],['budgets','Budgets',Wallet],['accounts','Accounts & settings',Landmark]] as const;
 return <div className="shell"><aside><a className="brand" href="#" onClick={e=>{e.preventDefault();setView("inbox");}}><span className="brand-symbol">◒</span> together</a><p className="eyebrow">YOUR DAILY CHECK-IN</p><nav>{tabs.map(([id,name,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>{setView(id);setNotice('');}}><span><Icon size={18}/>{name}</span>{id==='inbox'&&queue.length>0&&<b>{queue.length}</b>}</button>)}</nav><div className="sidebar-note"><div className="avatar-pair"><span>{s.you[0]}</span><span>{s.partner[0]}</span></div>A little clarity.<br/>Every day, together.</div></aside>
 <main><header><span className="eyebrow">A SHARED MONEY HABIT</span><div className="header-actions">{demo?<><span className="pill">Sample mode · not saved</span><button className="text-button" onClick={exitDemo}>Your household</button></>:<><span className="pill">{state.items.length?'Banks connected':'Banks not connected'}</span>{state.items.length>0&&<button className="icon-button" title="Sync bank transactions" aria-label="Sync bank transactions" disabled={busy} onClick={sync}><RotateCw size={17}/></button>}</>}</div></header>
 {error&&<div className="alert error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={17}/></button></div>}
 {notice&&<div className="alert notice" role="status">{notice}<button aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={17}/></button></div>}
 {loading?<section className="intro"><h1>Opening your check-in…</h1></section>:signedOut?<section className="welcome panel"><span className="brand-symbol">◒</span><h1>Your money.<br/>On the same page.</h1><p>A short check-in to review spending, agree on splits, and know where you both stand. Your backlog waits for you.</p><button className="primary" onClick={onExitDemo}>Return to sign-in</button><button className="secondary" onClick={startDemo}>Try sample transactions</button></section>:<>
 {view==='inbox'&&<><section className="intro"><div><div className="date-line"><Clock3 size={15}/>{new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}{checkedToday&&<span> · Checked in today</span>}</div><h1>{queue.length?<>A little check-in.<br/>A clearer picture.</>:<>A little space<br/>to get on the same page.</>}</h1><p>Pick up where you left off. Nothing resets at midnight.<br/>Your unreviewed transactions stay until you’re ready.</p></div><div className="count"><strong>{queue.length}</strong><span>waiting for you</span></div></section>
 <div className="checkin-strip"><span><Users size={18}/>{sessionCount?sessionCount+' reviewed this visit':'Make a little time for both of you'}</span><button className="text-button" onClick={finish} disabled={busy}><CheckCheck size={18}/>{checkedToday?'Save another check-in':'Done for today'}</button></div>
 <div className="workspace"><section className="panel inbox-panel"><div className="section-heading"><h2>Your review inbox</h2><button className="text-button" onClick={()=>setAdding(true)}><Plus size={17}/>Add</button></div><div className="segments">{[['unreviewed','To review',queue.length],['reviewed','Reviewed',reviewed.length],['pending','Pending',pending.length]].map(([id,label,n])=><button className={filter===id?'selected':''} onClick={()=>{setFilter(String(id));setSelected(null);}} key={id}>{label} <span>{n}</span></button>)}</div>
 {filter==='unreviewed'&&queue.length>0&&<div className="list-caption">Oldest first · includes your backlog</div>}
 {list.length? <div className="transaction-list">{list.map(t=><button className={'transaction '+(current?.id===t.id?'chosen':'')} key={t.id} onClick={()=>setSelected(t.id)}><div className={'merchant-icon '+(t.amount<0?'incoming':'')}>{t.amount<0?<ArrowDownLeft size={20}/>:t.merchant[0]}</div><div className="transaction-info"><strong>{t.merchant}</strong><p>{new Date(t.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})} · {t.payer==='you'?s.you:s.partner}{t.reviewed?' · '+t.category:''}</p></div><div className="amount">{t.amount<0?'+':''}{dollars(Math.abs(t.amount))}{!!t.reviewed&&<Check size={13}/>}</div></button>)}</div>:<div className="empty"><div className="empty-icon"><CheckCheck size={30}/></div><h2>{filter==='reviewed'?'Your picture starts here':filter==='pending'?'Nothing pending':transactions.length?'All caught up':'Start your daily habit'}</h2><p>{filter==='reviewed'?'Reviewed transactions will appear here.':filter==='pending'?'Transactions awaiting bank confirmation will appear here.':transactions.length?'Come back tomorrow. Anything new will wait here for you.':'Connect your banks or add a transaction to begin. You can also try the workflow with sample data.'}</p>{!transactions.length&&filter==='unreviewed'&&<div className="button-row"><button className="primary" onClick={()=>setView('accounts')}>Set up accounts</button><button className="secondary" onClick={startDemo}>Try a sample</button></div>}</div>}</section>
 {current?<Review key={current.id+':'+current.updated+':'+current.reviewed} transaction={current} settings={s} busy={busy} onSave={saveTransaction}/>:<section className="panel ritual"><p className="eyebrow">YOUR FIVE-MINUTE RITUAL</p><h2>Small habit.<br/>Shared understanding.</h2><ol><li><span>1</span><div><strong>See what came in</strong><p>Purchases and deposits from both of you.</p></div></li><li><span>2</span><div><strong>Agree on the details</strong><p>What it was for, and whose share it is.</p></div></li><li><span>3</span><div><strong>Leave on the same page</strong><p>See your spending and shared balance.</p></div></li></ol><button className="secondary" onClick={()=>setView('picture')}>See our picture <ChevronRight size={16}/></button></section>}</div></>}
 {view==='picture'&&<><section className="intro"><div><p className="eyebrow">OUR PICTURE</p><h1>Same numbers.<br/>Shared understanding.</h1><p>Based on reviewed transactions. {queue.length} still waiting for review.</p></div><label className="month-picker">Month<input aria-label="Report month" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></section><div className="stats-grid"><Stat label="Household spending" value={dollars(totals.spending)}/><Stat label={s.you+' · allocated share'} value={dollars(totals.you)}/><Stat label={s.partner+' · allocated share'} value={dollars(totals.partner)}/><Stat label="Income received" value={dollars(totals.income)}/></div><div className="workspace picture-grid"><section className="panel"><div className="section-heading"><h2>Where it went</h2><span>{month}</span></div><CategoryChart totals={totals.categories}/></section><section className="panel balance-card"><p className="eyebrow">BETWEEN YOU · ALL TIME</p><h2>{Math.abs(all.balance)<1?'You’re square':all.balance>0?s.partner+' owes '+s.you:s.you+' owes '+s.partner}</h2><div className="balance-value">{dollars(Math.abs(all.balance))}</div><p>Agreed shares, minus repayments, across all reviewed history. A starting balance is not imported automatically.</p><div className="contribution"><span>Paid this month</span><span>Allocated share</span></div>{[['you',s.you,totals.youPaid,totals.you],['partner',s.partner,totals.partnerPaid,totals.partner]].map(([id,name,paid,share])=><div className="contribution" key={id}><strong>{name}<small>{dollars(Number(paid))}</small></strong><strong>{dollars(Number(share))}</strong></div>)}<p className="small">Paying more doesn’t always mean owing less. Your agreed split determines the balance.</p></section></div><section className="panel chart-panel"><h2>Spending through the month</h2><Trend values={totals.daily} month={month}/></section></>}
 {view==='budgets'&&<><section className="intro"><div><p className="eyebrow">ROOM FOR WHAT MATTERS</p><h1>A plan you<br/>make together.</h1><p>Monthly household limits, compared with reviewed spending.</p></div><label className="month-picker">Month<input aria-label="Budget month" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></section><BudgetEditor key={JSON.stringify(s.budgets)} settings={s} totals={totals.categories} onSave={saveSettings} busy={busy}/><p className="small">These limits repeat each month. No rollover. Individual spending shares appear in Our picture.</p></>}
 {view==='accounts'&&<><section className="intro"><div><p className="eyebrow">YOUR HOUSEHOLD</p><h1>Two people.<br/>One clear picture.</h1><p>Bring both sets of transactions into the same daily check-in.</p></div></section><div className="workspace"><section className="panel"><h2>Bank connections</h2><p>Connect each account once. For now, select one owner per connection; do not connect a joint account twice.</p>{demo?<div className="inline-note">You’re trying sample transactions. Switch to your household to connect real accounts.</div>:!state.bankReady?<div className="inline-note"><strong>Live bank setup is not complete</strong><p>Your Plaid account needs production access and its credentials securely configured before either bank can connect. Manual entries work now.</p></div>:<div className="inline-note">{state.bankEnvironment==='sandbox'?'Plaid Sandbox is active. Connections use test data, not real banks.':'Bank connection is ready. Each person signs in to their own bank through Plaid.'}</div>}
 {!demo&&state.bankReady&&<div className="button-row"><button className="primary" disabled={busy||state.memberRole!=='you'} onClick={()=>openLink('you')}>Connect {s.you}’s bank</button><button className="secondary" disabled={busy||state.memberRole!=='partner'} onClick={()=>openLink('partner')}>Connect {s.partner}’s bank</button></div>}
 {state.items.map(item=><div className="bank-row" key={item.id}><Landmark size={22}/><div><strong>{item.institution}</strong><p>{item.payer==='you'?s.you:s.partner} · {item.synced?'Last sync '+new Date(item.synced).toLocaleString():'Waiting for first sync'}</p>{item.error&&<p className="error-text">{item.error}</p>}<div className="button-row"><button className="text-button" disabled={busy||state.memberRole!==item.payer} onClick={()=>openLink(item.payer,item.id)}>Reconnect</button><button className="text-button" disabled={busy||state.memberRole!==item.payer} onClick={()=>{if(confirm('Disconnect this bank? Your imported transactions and reviews will stay.'))void run(async()=>{await api('bank',{action:'disconnect',itemId:item.id});await refresh();});}}>Disconnect</button></div></div></div>)}
 <p className="small">Transactions sync when you open the app or press Sync. Pending transactions wait for bank confirmation before review.</p><button className="secondary" onClick={()=>setAdding(true)}><Plus size={17}/>Add a transaction manually</button></section><section className="panel"><SettingsEditor settings={s} onSave={saveSettings} busy={busy}/><div className="privacy-note"><Users size={20}/><p>Your household is private to its two members. Reviews and budgets are shared across both computers. Each person connects their own bank while signed in.</p></div>{!demo&&state.memberRole==="you"&&state.memberCount===1&&<button className="secondary" onClick={()=>run(async()=>{const result=await native("household/invite");setNotice("Invite code (valid for 24 hours): "+result.inviteCode);})}>Create partner invite code</button>}<button className="text-button" onClick={demo?exitDemo:startDemo}>{demo?'Return to your household':'Try the workflow with sample data'}</button></section></div></>}
 </>}
 {adding&&<div className="modal-backdrop" onClick={()=>!busy&&setAdding(false)}><section className="modal panel" role="dialog" aria-modal="true" aria-labelledby="add-title" onClick={e=>e.stopPropagation()}><div className="section-heading"><h2 id="add-title">Add a transaction</h2><button aria-label="Close add transaction" onClick={()=>setAdding(false)} disabled={busy}><X/></button></div><ManualForm settings={s} busy={busy} onSave={saveTransaction}/></section></div>}
 </main></div>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="panel stat"><span>{label}</span><strong>{value}</strong></div>;}
function Review({transaction:t,settings:s,busy,onSave}:{transaction:Transaction;settings:Settings;busy:boolean;onSave:(t:Transaction)=>Promise<void>}){
 const [kind,setKind]=useState(t.kind),[category,setCategory]=useState(t.category),[share,setShare]=useState(t.share),[note,setNote]=useState(t.note);
 const allocation=shares({...t,share});const spending=kind==='expense'||kind==='refund';
 return <section className="panel review-card"><p className="eyebrow">{t.pending?'WAITING FOR YOUR BANK':t.reviewed?'REVIEWED TRANSACTION':'ONE AT A TIME'}</p><h2>{t.merchant}</h2><div className="review-amount">{t.amount<0?'+':''}{dollars(Math.abs(t.amount))}</div><p>{t.account} · {t.payer==='you'?s.you:s.partner} {t.amount<0?'received':'paid'}<br/>{new Date(t.date+'T12:00:00').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</p>
 {t.pending?<div className="inline-note">The amount can still change. This stays in Pending until your bank confirms it, then moves into your review inbox.</div>:<form onSubmit={e=>{e.preventDefault();void onSave({...t,kind,category,share,note,reviewed:1});}}><label>What kind of transaction?<select value={kind} onChange={e=>setKind(e.target.value as Transaction['kind'])}>{Object.entries(kindNames).filter(([id])=>t.amount>0?!['income','refund'].includes(id):id!=='expense').map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
 {spending&&<><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Whose expense is it?</label><div className="split-presets"><button type="button" className={share===100?'selected':''} onClick={()=>setShare(100)}>{s.you} only</button><button type="button" className={share===50?'selected':''} onClick={()=>setShare(50)}>50 / 50</button><button type="button" className={share===0?'selected':''} onClick={()=>setShare(0)}>{s.partner} only</button></div><label>Share for {s.you} (%)<input aria-label="Your share percentage" type="number" min="0" max="100" step="1" value={share} onChange={e=>setShare(Number(e.target.value))} required/></label><input aria-label="Adjust your share" type="range" min="0" max="100" value={share} onChange={e=>setShare(Number(e.target.value))}/><div className="split-label"><span><i className="dot yours"/>{s.you}<strong>{dollars(allocation.you)}</strong></span><span><i className="dot theirs"/>{s.partner}<strong>{dollars(allocation.partner)}</strong></span></div></>}
 {kind==='settlement'&&<div className="inline-note"><strong>Count the repayment once</strong><p>If this same payment appears in both accounts, review the other side as “Transfer / card payment.” Otherwise the repayment would count twice. Repayments don’t change your spending or income.</p></div>}
 {kind==='transfer'&&<div className="inline-note">Excluded from spending, income, and the balance between you. Use this for transfers, credit-card payments, or the second side of a repayment.</div>}
 {kind==='income'&&<div className="inline-note">Counts as income received. Money from your partner should usually be a repayment or transfer.</div>}
 {kind==='refund'&&<div className="inline-note">Reduces spending in this category. Use the same split as the original purchase.</div>}
 <label>Note <span className="optional">(optional)</span><input value={note} maxLength={1000} onChange={e=>setNote(e.target.value)} placeholder="Anything you want to remember"/></label><button className="primary" disabled={busy||share<0||share>100} type="submit"><Check size={18}/>{busy?'Saving…':t.reviewed?'Save changes':'Confirm & next'}</button>{!!t.reviewed&&<button className="text-button undo" type="button" disabled={busy} onClick={()=>onSave({...t,reviewed:0})}><Undo2 size={15}/>Move back to inbox</button>}</form>}</section>;
}
function BudgetEditor({settings,totals,busy,onSave}:{settings:Settings;totals:Record<string,number>;busy:boolean;onSave:(s:Settings)=>Promise<void>}){
 const [budgets,setBudgets]=useState<Record<string,string>>(Object.fromEntries(categories.map(c=>[c,settings.budgets[c]===undefined?'':String(settings.budgets[c]/100)])));
 return <form onSubmit={e=>{e.preventDefault();void onSave({...settings,budgets:Object.fromEntries(Object.entries(budgets).filter(([,v])=>v!=='').map(([k,v])=>[k,Math.round(Number(v)*100)]))});}}><div className="budget-grid">{categories.map(c=>{const spent=totals[c]||0,limit=Number(budgets[c])*100,has=budgets[c]!=='';return <section className="panel budget-card" key={c}><div className="section-heading"><h2>{c}</h2><span>{dollars(spent)} spent</span></div><div className="budget-track"><div className={has&&spent>limit?'over':''} style={{width:has&&limit?Math.max(0,Math.min(100,spent/limit*100))+'%':'0%'}}/></div><p className={has&&spent>limit?'error-text':''}>{has?dollars(Math.abs(limit-spent))+(spent>limit?' over budget':' remaining'):'No budget set'}</p><label>Monthly limit ($)<input type="number" min="0" step=".01" placeholder="Not set" value={budgets[c]} onChange={e=>setBudgets(b=>({...b,[c]:e.target.value}))}/></label></section>;})}</div><button className="primary save-budgets" disabled={busy}>Save monthly budgets</button></form>;
}
function SettingsEditor({settings:s,busy,onSave}:{settings:Settings;busy:boolean;onSave:(s:Settings)=>Promise<void>}){
 const [you,setYou]=useState(s.you),[partner,setPartner]=useState(s.partner),[share,setShare]=useState(s.defaultShare);
 return <form onSubmit={e=>{e.preventDefault();void onSave({...s,you,partner,defaultShare:share});}}><h2>Make it yours</h2><div className="form-columns"><label>Your name<input maxLength={30} value={you} onChange={e=>setYou(e.target.value)} required/></label><label>Partner’s name<input maxLength={30} value={partner} onChange={e=>setPartner(e.target.value)} required/></label></div><label>Default share for {you||'you'} (%)<input type="number" min="0" max="100" step="1" value={share} onChange={e=>setShare(Number(e.target.value))} required/></label><p className="small">A starting suggestion for new transactions. Every split is yours to confirm, and previous reviews stay as they are.</p><button className="primary" disabled={busy}>Save household settings</button></form>;
}
function ManualForm({settings:s,busy,onSave}:{settings:Settings;busy:boolean;onSave:(t:Transaction)=>Promise<void>}){
 const [merchant,setMerchant]=useState(''),[amount,setAmount]=useState(''),[direction,setDirection]=useState('out'),[payer,setPayer]=useState<'you'|'partner'>('you'),[date,setDate]=useState(localDay());
 const [id]=useState(()=> 'manual-'+crypto.randomUUID());
 return <form onSubmit={e=>{e.preventDefault();const cents=Math.round(Number(amount)*100)*(direction==='out'?1:-1);void onSave({id,date,merchant,amount:cents,payer,kind:direction==='out'?'expense':'income',category:'Other',share:s.defaultShare,note:'',reviewed:0,pending:0,source:'manual',account:'Manual entry'});}}><label>Merchant or description<input autoFocus value={merchant} maxLength={160} onChange={e=>setMerchant(e.target.value)} required/></label><div className="form-columns"><label>Amount ($)<input type="number" min=".01" max="10000000" step=".01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Direction<select value={direction} onChange={e=>setDirection(e.target.value)}><option value="out">Money out</option><option value="in">Money in</option></select></label></div><label>Account owner<select value={payer} onChange={e=>setPayer(e.target.value as any)}><option value="you">{s.you}</option><option value="partner">{s.partner}</option></select></label><label>Transaction date<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><p className="small">Next, review the category and split in your inbox. Manual entries are not automatically matched to later bank imports.</p><button className="primary" disabled={busy}>Add to review inbox</button></form>;
}
function CategoryChart({totals}:{totals:Record<string,number>}){
 const rows=Object.entries(totals).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...rows.map(([,v])=>Math.abs(v)));
 return rows.length?<div className="category-chart">{rows.map(([c,v],i)=><div key={c}><div className="bar-label"><span>{c}</span><strong>{dollars(v)}</strong></div><div className="bar-track"><div style={{width:Math.abs(v)/max*100+'%',background:['#7564dc','#9c92e9','#758db5','#adc0d9'][i%4]}}/></div></div>)}</div>:<div className="empty"><ChartNoAxesCombined size={34}/><p>Review purchases to see your spending by category.</p></div>;
}
function Trend({values,month}:{values:Record<string,number>;month:string}){
 const days=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate()||31;let cumulative=0;const amounts=Array.from({length:days},(_,i)=>{cumulative+=values[month+'-'+String(i+1).padStart(2,'0')]||0;return cumulative;});const max=Math.max(1,...amounts),min=Math.min(0,...amounts);const y=(v:number)=>160-(v-min)/(max-min)*135;const points=amounts.map((v,i)=>((i/(days-1))*740+10)+','+y(v)).join(' ');
 return <div className="trend"><div className="bar-label"><span>Cumulative reviewed spending</span><strong>{dollars(cumulative)}</strong></div><svg viewBox="0 0 760 180" role="img" aria-label={'Cumulative spending for '+month+': '+dollars(cumulative)}><line x1="10" y1="160" x2="750" y2="160" stroke="#e4e8f0"/><line x1="10" y1="90" x2="750" y2="90" stroke="#edf0f5"/><polygon points={'10,170 '+points+' 750,170'} fill="#f0edff"/><polyline points={points} fill="none" stroke="#7867df" strokeWidth="3" strokeLinejoin="round"/></svg><div className="bar-label"><span>1 {new Date(month+'-01T12:00:00').toLocaleDateString('en-US',{month:'short'})}</span><span>{days} {new Date(month+'-01T12:00:00').toLocaleDateString('en-US',{month:'short'})}</span></div></div>;
}



