const {app,BrowserWindow,ipcMain,safeStorage,Notification,shell,Menu}=require('electron');
const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');const {autoUpdater}=require('electron-updater');
let win,session=null,config={},updateState={status:'idle'},updaterConfigured=false,refreshing=null,remindedDay='';
const filename=()=>path.join(app.getPath('userData'),'preferences.json');
const tokenFile=()=>path.join(app.getPath('userData'),'session.enc');
function saveConfig(){fs.mkdirSync(app.getPath('userData'),{recursive:true});fs.writeFileSync(filename()+'.tmp',JSON.stringify(config));fs.renameSync(filename()+'.tmp',filename());}
function saveSession(value){session=value;if(!value){fs.rmSync(tokenFile(),{force:true});return;}if(!safeStorage.isEncryptionAvailable())throw new Error('Your operating system’s secure storage is unavailable. Please sign in again after enabling it.');fs.writeFileSync(tokenFile()+'.tmp',safeStorage.encryptString(JSON.stringify(value)),{mode:0o600});fs.renameSync(tokenFile()+'.tmp',tokenFile());}
function load(){try{config=JSON.parse(fs.readFileSync(path.join(__dirname,'service.json'),'utf8'));}catch{}try{config={...config,...JSON.parse(fs.readFileSync(filename(),'utf8'))};}catch{}try{if(safeStorage.isEncryptionAvailable())session=JSON.parse(safeStorage.decryptString(fs.readFileSync(tokenFile())));}catch{session=null;}}
function validConfig(value){const url=new URL(value.supabaseUrl);if(url.protocol!=='https:'||!url.hostname.endsWith('.supabase.co')||url.pathname!=='/'||url.search||url.username||url.password)throw new Error('Enter your project URL, such as https://your-project.supabase.co.');const key=String(value.supabaseKey||'').trim();if(key.startsWith('sb_secret_'))throw new Error('Use the publishable key, never a secret key.');if(!key.startsWith('sb_publishable_')){try{const claims=JSON.parse(Buffer.from(key.split('.')[1],'base64url').toString());if(claims.role!=='anon')throw Error();}catch{throw new Error('Use the Supabase publishable key or legacy anon key.');}}return {supabaseUrl:url.origin,supabaseKey:key};}
async function authRequest(endpoint,body){const r=await fetch(config.supabaseUrl+'/auth/v1/'+endpoint,{method:'POST',headers:{apikey:config.supabaseKey,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.msg||d.error_description||d.message||'Sign-in could not complete.');return d;}
async function accessToken(){if(!session)throw new Error('Please sign in.');if((session.expires_at||0)*1000<Date.now()+60000){if(!refreshing)refreshing=authRequest('token?grant_type=refresh_token',{refresh_token:session.refresh_token}).then(s=>{saveSession(s);return s;}).catch(e=>{saveSession(null);throw e;}).finally(()=>{refreshing=null;});await refreshing;}return session.access_token;}
async function backend(action,args={}){const token=await accessToken();const r=await fetch(config.supabaseUrl+'/functions/v1/household',{method:'POST',headers:{apikey:config.supabaseKey,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({...args,action})});let data;try{data=await r.json();}catch{throw new Error('The household service did not respond. Check your connection and service setup.');}if(!r.ok)throw new Error(data.error||'Your household could not be loaded.');return data;}
function status(state){updateState=state;if(win&&!win.isDestroyed())win.webContents.send('update-state',state);}
function setupUpdates(){if(!app.isPackaged||!config.updateRepository||!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(config.updateRepository)){status({status:'unconfigured'});return;}const [owner,repo]=config.updateRepository.split('/');autoUpdater.setFeedURL({provider:'github',owner,repo,private:false});autoUpdater.autoDownload=false;autoUpdater.autoInstallOnAppQuit=false;autoUpdater.allowDowngrade=false;updaterConfigured=true;autoUpdater.on('checking-for-update',()=>status({status:'checking'}));autoUpdater.on('update-available',info=>status({status:'available',version:info.version}));autoUpdater.on('update-not-available',()=>status({status:'current'}));autoUpdater.on('download-progress',progress=>status({status:'downloading',percent:Math.round(progress.percent)}));autoUpdater.on('update-downloaded',info=>status({status:'downloaded',version:info.version}));autoUpdater.on('error',()=>status({status:'error',message:'Could not check or download this update. Try again later.'}));setTimeout(()=>void checkUpdates(),8000);setInterval(()=>void checkUpdates(),3600000).unref();}
async function checkUpdates(){if(!updaterConfigured)return updateState;if(['available','downloading','downloaded','checking'].includes(updateState.status))return updateState;try{await autoUpdater.checkForUpdates();}catch{}return updateState;}
function createWindow(){win=new BrowserWindow({width:1300,height:900,show:!process.env.TOGETHER_SMOKE_TEST,icon:path.join(__dirname,'../build/icon.png'),minWidth:800,minHeight:650,title:'Together',backgroundColor:'#f4f6fa',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,webSecurity:true}});Menu.setApplicationMenu(Menu.buildFromTemplate([{label:'Together',submenu:[{role:'about'},{role:'quit'}]},{label:'Edit',submenu:[{role:'undo'},{role:'redo'},{type:'separator'},{role:'cut'},{role:'copy'},{role:'paste'},{role:'selectAll'}]},{label:'View',submenu:[{role:'reload'},{role:'resetZoom'},{role:'zoomIn'},{role:'zoomOut'},{role:'togglefullscreen'}]}]));win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',(event,url)=>{if(url!==pathToFileURL(path.join(__dirname,'../dist/index.html')).href)event.preventDefault();});win.webContents.session.setPermissionRequestHandler((_webContents,_permission,callback)=>callback(false));if(process.env.TOGETHER_SMOKE_TEST){win.webContents.on('did-fail-load',(_e,code,description)=>{console.error('Desktop load failed',code,description);app.exit(1);});win.webContents.on('render-process-gone',()=>app.exit(1));win.webContents.on('did-finish-load',()=>setTimeout(()=>{console.log('Desktop window loaded successfully');app.quit();},1500));}win.loadFile(path.join(__dirname,'../dist/index.html'));win.on('focus',()=>{if(updaterConfigured&&['idle','current','error'].includes(updateState.status))void checkUpdates();});}
function trust(event){const expected=pathToFileURL(path.join(__dirname,'../dist/index.html')).href;if(event.sender!==win?.webContents||event.senderFrame?.url.split('#')[0]!==expected)throw new Error('Untrusted app request.');}
ipcMain.handle('together',async(event,action,args={})=>{try{trust(event);if(typeof action!=='string'||JSON.stringify(args).length>30000)throw new Error('Invalid request.');
 if(action==='bootstrap')return {ok:true,data:{configured:!!config.supabaseUrl,email:session?.user?.email||null,version:app.getVersion(),update:updateState,reminder:config.reminder||'20:00',remindersEnabled:config.remindersEnabled!==false}};
 if(action==='configure'){const validated=validConfig(args);config={...config,...validated};saveConfig();saveSession(null);return {ok:true,data:{ok:true}};}
 if(action==='signin'){const value=await authRequest('token?grant_type=password',{email:args.email,password:args.password});saveSession(value);return {ok:true,data:{email:value.user.email}};}
 if(action==='signup'){const value=await authRequest('signup',{email:args.email,password:args.password});if(value.access_token)saveSession(value);return {ok:true,data:{signedIn:!!value.access_token,message:value.access_token?'Account created.':'Check your email to confirm your account, then sign in here.'}};}
 if(action==='signout'){try{const token=await accessToken();await fetch(config.supabaseUrl+'/auth/v1/logout',{method:'POST',headers:{apikey:config.supabaseKey,Authorization:'Bearer '+token}});}catch{}saveSession(null);return {ok:true,data:{ok:true}};}
 if(action==='reminder'){if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(args.time))throw new Error('Choose a valid reminder time.');config.reminder=args.time;config.remindersEnabled=!!args.enabled;saveConfig();return {ok:true,data:{ok:true}};}
 if(action==='updates/check')return {ok:true,data:await checkUpdates()};
 if(action==='updates/download'){if(updateState.status!=='available')throw new Error('No update is ready to download.');void autoUpdater.downloadUpdate().catch(()=>{});return {ok:true,data:{ok:true}};}
 if(action==='updates/install'){if(updateState.status!=='downloaded')throw new Error('Download the update first.');setImmediate(()=>autoUpdater.quitAndInstall(false,true));return {ok:true,data:{ok:true}};}
 if(action==='bank/open'){const result=await backend('bank/link',args);const url=new URL(result.url);if(url.protocol!=='https:'||url.hostname!=='secure.plaid.com')throw new Error('Unexpected bank connection address.');await shell.openExternal(url.href);return {ok:true,data:{sessionId:result.sessionId}};}
 const allowed=new Set(['state','transactions','settings','checkin','household/create','household/join','household/invite','bank/sync','bank/poll','bank/disconnect']);if(!allowed.has(action))throw new Error('Unknown action.');return {ok:true,data:await backend(action,args)};
 }catch(e){return {ok:false,error:e.message||'The request could not complete.'};}});
const lock=app.requestSingleInstanceLock();if(!lock)app.quit();else{app.on('second-instance',()=>{if(win){if(win.isMinimized())win.restore();win.show();win.focus();}});app.whenReady().then(()=>{load();createWindow();setupUpdates();setInterval(()=>{if(config.remindersEnabled===false)return;const now=new Date(),day=now.toLocaleDateString('en-CA'),time=String(now.getHours()).padStart(2,'0')+':'+String(now.getMinutes()).padStart(2,'0');if(time===(config.reminder||'20:00')&&day!==remindedDay&&Notification.isSupported()){remindedDay=day;const n=new Notification({title:'Your Together check-in',body:'Take a few minutes together to review your transactions. Your backlog is waiting.'});n.on('click',()=>{win?.show();win?.focus();});n.show();}},30000).unref();});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit();});app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();});}


